### ISSUE TITLE
Import standardized BLUEPRINT data from TrackHub repo

### ISSUE THREAD

**Issue by sveinugu** [elixir-no-nels/trackfind#101]
Once we have confirmation and info on the FAIR BLUEPRINT metadata being available from the TrackHub Registry (https://github.com/orgs/fairtracks/teams/fairtracks-developers/discussions/44), we should implement crawling and handling of FAIRtracks metadata from THR. This has to be working before the webinar.

**Comment by dtitov** [comment]
Blocked due to the corresponding hub is not available in THR after one of the recent schema changes. Pending update from Kieron.
