### ISSUE TITLE
Remove @schema from the categories list

### ISSUE THREAD

**Issue by dtitov** [elixir-no-nels/trackfind#78]

**Comment by sveinugu** [comment]
@dtitov I saw you hard-coded the removal of the string "@schema" only, which is really only a part of the fairtracks standard, and not anything generic. I think we instead should make a natural rule, e.g. remove all attributes starting with a non-alphanumeric letter, or similar?

**Comment by sveinugu** [comment]
Whoops. Now I notified GitHub user Schema! :) Sorry

**Comment by dtitov** [comment]
Sure. Do you know if there are some common rules for this in the JSON schema specs?

**Comment by sveinugu** [comment]
No, I don't think so. But I am not sure

**Comment by sveinugu** [comment]
Seems one mostly uses alphanumerics, underscore, and dollar. https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format https://github.com/zalando/restful-api-guidelines/issues/32#property-naming

**Comment by dtitov** [comment]
Ok, so I can add a rule that the property will be ignored if it doesn't start with a letter, `_` or `$`?

**Comment by sveinugu** [comment]
But I think underscore and dollars are also typically special properties. Ignore everything that is non-alphanumeric is my intuition.

**Comment by sveinugu** [comment]
Does not start with letter or number, I mean

**Comment by dtitov** [comment]
Deal.

**Comment by dtitov** [comment]
https://github.com/elixir-no-nels/trackfind/commit/dbcdf80c5dd10a1091780174a5c94a9be459ca4b
