### ISSUE TITLE
Some samples are "detached" in Blueprint repo

### ISSUE THREAD

**Issue by dtitov** [elixir-no-nels/trackfind#81]
Some samples (e.g. `DG-75_c01`) are not referenced by any experiment.

**Comment by sveinugu** [comment]
@dtitov Is this a solution, though? We intend to change into getting the json from TrackHub once they have incorporated it as part of the standard content. So I think Daniel should be on top of all changes in the blueprint json. I also have some other requests for him pending.

**Comment by dtitov** [comment]
Well, this dump is the current source for the FAIRified Blueprint - we don't have any other, because Blueprint from THR is not standardized yet. We've been using it as a temp work-around and this fix is for this temp work-around. Of course, all relevant changes should be then reflected in the real endpoint of the THR.

**Comment by sveinugu** [comment]
Ah, just saw this: https://github.com/orgs/fairtracks/teams/fairtracks-developers/discussions/38. Then everything is fine. I thought you just removed the samples yourself.. Sorry
