### ISSUE TITLE
Add cache on search queries

### ISSUE THREAD

**Issue by sveinugu** [elixir-no-nels/trackfind#93]

**Comment by sveinugu** [comment]
The HB client has to carry out the same search query several times, due to limitations in ProTo. Perhaps a general cache on search queries could fix this? Should then cache the gsuite file, if possible. Also cache on other endpoints would be useful (values/attributes)

**Comment by sveinugu** [comment]
Closed, but no commits?

**Comment by dtitov** [comment]
https://github.com/elixir-no-nels/trackfind/commit/4aef348dc4017ff3ec1edea248add9b3e3056a4c

I just forgot to link commit :)
