### ISSUE TITLE
Some examples of API usage

### ISSUE THREAD

**Issue by jmfernandez** [elixir-no-nels/trackfind#98]
Although https://app.swaggerhub.com/apis-docs/dtitov/TrackFind/1.0.0 is a nice way to test the API capabilities, for the `search` endpoint I'm missing some examples (I found some inspiration from [Tests.kt](//github.com/elixir-no-nels/trackfind/blob/master/int-tests/src/test/kotlin/no/uio/ifi/inttests/Tests.kt).

Could you write an examples file, like a "cheatsheet" of chain-able REST calls, please?

**Comment by dtitov** [comment]
Yes, we should definitely do that. And we already have an issue for the documentation: https://github.com/elixir-no-nels/trackfind/issues/70

The "cheatsheet" that you suggest is going to be a part of this documentation. So I will close this issue in favour of that one.
