### ISSUE TITLE
Add horisontal scroll bar to model browser

### ISSUE THREAD

**Issue by sveinugu** [elixir-no-nels/trackfind#99]
**Is your feature request related to a problem? Please describe.**
It is not possible to read full values that are larger than the model browser box, at least on Chrome (MacOS)

**Describe the solution you'd like**
Add horisontal scroll bar

**Comment by dtitov** [comment]
This is strange, because I do have horizontal scrollbar there: https://vimeo.com/367229679

What version of Chrome are you using? I have: `Version 77.0.3865.120 (Official Build) (64-bit)`

**Comment by sveinugu** [comment]
Google Chrome is up to date
Version 77.0.3865.120 (Official Build) (64-bit)

**Comment by sveinugu** [comment]
High sierra OS

**Comment by sveinugu** [comment]
I get horisontal scroll bars in your example also! But try the original Blueprint_Hub, data->SAMPLE_ONTOLOGY_URI

**Comment by dtitov** [comment]
I have it there as well 🤷‍♂️

![](https://habrastorage.org/webt/f2/tm/op/f2tmop1jmiru8s6umpmdew_esbo.png)

**Comment by sveinugu** [comment]
Strange. Probably some OS issue. You can close the issue, I think.
